### ISSUE TITLE
Query option for selecting database

### ISSUE THREAD

**Issue by lqst** [denniskniep/grafana-datasource-plugin-neo4j#32]
If not already supported, it would be nice to be able to select the database (not the url but the name of the database inside the cluster) to execute the cypher query against from the Query Options. As of now, I have only been able to set the database in the data source configuration like this:

```yaml
name: Neo4j Cluster
    type: kniepdennis-neo4j-datasource
    access: proxy
    jsonData:
      database: demo
      url...
```
